version: '3.5'
services:
    backend: 
      build:
        dockerfile: Dockerfile 
        context: .
      ports: 
        - 4000:4000
      depends_on: 
        - database 
      networks: 
        - snippetbox-network
      restart: on-failure 

    database:
      image: mysql:5.7
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: snippetbox
          MYSQL_USER: web
          MYSQL_PASSWORD: 123
      volumes:
          - "db-volume:/var/lib/mysql"
          - "./scripts/InitializeDatabase.sql:/docker-entrypoint-initdb.d/InitializeDatabase.sql"
      networks: 
        - snippetbox-network
      command: ["--init-file", "/docker-entrypoint-initdb.d/InitializeDatabase.sql", "--datadir", "/var/lib/mysql"]


volumes:
    db-volume:

networks: 
    snippetbox-network: 