version: '3.5'
services:
    backend: 
      build:
        dockerfile: Dockerfile 
        context: .
      ports: 
        - 4000:4000
      depends_on: 
        - database 
      networks: 
        - snippetbox-network

    database:
      build:
        dockerfile: infra/db/Dockerfile  
        context: .
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: snippetbox
          MYSQL_USER: web
          MYSQL_PASSWORD: 123
      volumes:
          - db-volume:/var/lib/mysql
      networks: 
        - snippetbox-network

volumes:
    db-volume:

networks: 
    snippetbox-network: 